add_newline = false
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration$jobs\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
style = "#689d6a"
read_only = " "
truncation_length = 4
truncate_to_repo = false
home_symbol = "~"
format = "[$path]($style)[$read_only]($read_only_style) "

[character]
success_symbol = "[;](#b16286)"
error_symbol = "[;](#cc241d)"
vicmd_symbol = "[;](#98971a)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "#928374"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "#458588"
modified = "âœ±"
untracked = "âœ±"
deleted = "âœ±"
renamed = "âœ±"
staged = "âœ±"
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"

[git_metrics]
disabled = true

[cmd_duration]
format = "[$duration]($style) "
style = "#d79921"
min_time = 2000
show_milliseconds = false

[jobs]
symbol = ""
style = "bold #cc241d"
number_threshold = 1
format = "[$symbol]($style)"

[nodejs]
format = "[$symbol($version )]($style)"
style = "#98971a"
symbol = " "

[package]
format = "[$symbol$version]($style) "
style = "#d79921"
symbol = "ðŸ“¦ "

[username]
style_user = "#98971a"
style_root = "#cc241d"
format = "[$user]($style) "
disabled = false
show_always = false

[hostname]
ssh_only = true
format = "[$hostname](bold #d65d0f) "
disabled = false
