
# note : this should be under .config/alacritty/alacritty.toml

# =============================
# Font configuration
# =============================
[font]
size = 14.5
builtin_box_drawing = true

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.bold]
family = "Iosevka Term"
style = "Bold"

# =============================
# Window configuration
# =============================
[window]
decorations = "None"
#dynamic_padding = true
#startup_mode = "Windowed"
option_as_alt = "Both"

 [window.padding]
 x = 4
 y = 4

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Beam"

# =============================

